BOL_SCHEMA = {
    "type": "object",
    "properties": {
        "document_type": {"type": "string", "enum": ["BOL", "POD", "unknown"]},
        "shipper_name": {"type": ["string", "null"]},
        "shipper_address": {"type": ["string", "null"]},
        "consignee_name": {"type": ["string", "null"]},
        "consignee_address": {"type": ["string", "null"]},
        "carrier_name": {"type": ["string", "null"]},
        "load_number": {"type": ["string", "null"]},
        "pro_number": {"type": ["string", "null"]},
        "pickup_date": {"type": ["string", "null"], "description": "YYYY-MM-DD if determinable"},
        "delivery_date": {"type": ["string", "null"], "description": "YYYY-MM-DD if determinable"},
        "weight": {"type": ["number", "null"]},
        "weight_unit": {"type": ["string", "null"], "enum": ["lb", "kg", None]},
        "piece_count": {"type": ["integer", "null"]},
        "commodity_description": {"type": ["string", "null"]},
        "freight_charge_terms": {
            "type": ["string", "null"],
            "enum": ["prepaid", "collect", "third_party", None],
        },
        "signature_present": {"type": ["boolean", "null"]},
        "review_recommended": {"type": "boolean"},
        "extraction_notes": {"type": ["string", "null"]},
    },
    "required": ["document_type", "review_recommended"],
    "additionalProperties": False,
}

FIELD_ORDER = [
    "document_type",
    "shipper_name",
    "shipper_address",
    "consignee_name",
    "consignee_address",
    "carrier_name",
    "load_number",
    "pro_number",
    "pickup_date",
    "delivery_date",
    "weight",
    "weight_unit",
    "piece_count",
    "commodity_description",
    "freight_charge_terms",
    "signature_present",
    "review_recommended",
    "extraction_notes",
]
